name: Build & Test

on:
  push:
    branches: [ lost ]
  pull_request:
    branches: [ lost ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Restore dependencies
        run: dotnet restore Tests/Tests.csproj
      - name: Build
        run: dotnet build --no-restore Tests/Tests.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal Tests/Tests.csproj